
CREATE TABLE STUDENT(
	ID NUMBER(3),
	NAME VARCHAR2(20),

	MAJOR VARCHAR2(20),
	--조건식 : TRUE, FALSE 두 가지의 결과로 나오는 식
	--컬럼명 IN (값1, 값2, ...) : 값1 OR 값2 OR ...
	GENDER CHAR(1) CONSTRAINT BAN_CHAR CHECK(GENDER IN ('M', 'W')),
	BIRTH DATE CONSTRAINT BAN_DATE CHECK(BIRTH >= TO_DATE('1980-01-01', 'YYYY-MM-DD')),
	CONSTRAINT STD_PK PRIMARY KEY(ID)
);

SELECT * FROM STUDENT


INSERT INTO HR.STUDENT
(ID, NAME, MAJOR, GENDER, BIRTH)
VALUES(1, '최한빈', '경영학', 'M', TO_DATE('2000/02/17', 'YYYY/MM/DD'));
--dbms > Oracle > Schemas > HR > STUDENT > GENERAL INSERT > copy


INSERT INTO HR.STUDENT
(ID, NAME, MAJOR, GENDER, BIRTH)
VALUES(2, '최한빈', '경영학', 'M', TO_DATE('19900725', 'YYYYMMDD'));
-- TO_DATE 형식 구글링

SELECT * FROM STUDENT

DROP TABLE STUDENT

--영화 정보 테이블
-- 배우
-- 장르
-- 제목
-- 감독
-- 개봉일
-- 19세

CREATE TABLE MOVIE(
	ACTOR VARCHAR2(20),
	GENRE VARCHAR2(20),
	TITLE VARCHAR2(20),
	DIRECTOR VARCHAR2(20),
	PUBLISH_DATE DATE,
	ADULT CHAR(1) CONSTRAINTS BAN_ADULT CHECK(ADULT IN ('Y', 'N'))
);

INSERT INTO MOVIE(ACTOR, GENRE, TITLE, DIRECTOR, PUBLISH_DATE, ADULT)
VALUES('최한빈', '로맨스', '다시', '최한빈', TO_DATE('20-08-07', 'YY-MM-DD'), 'Y');

SELECT * FROM MOVIE

CREATE TABLE MOVIE2(
	ACTOR VARCHAR2(500),
	GENRE VARCHAR2(20),
	TITLE VARCHAR2(100),
	DIRECTOR VARCHAR2(20),
	MOVIEDATE DATE CONSTRAINT M_DATE CHECK(MOVIEDATE >= TO_DATE('1990-01-01', 'YYYY-MM-DD')),
	AGE CHAR(2) CONSTRAINT M_AGE CHECK(AGE IN ('AA', '19'))
);


--반정규화(,를 기준으로 나눔)
--TO_DATE() 함수는 통채로가 '시간 데이터'이다.
INSERT INTO MOVIE2 VALUES('황정민, 박정민, 이정재, 최희서', '범죄', '다악구', '홍원찬', TO_DATE('2020-08-05', 'YYYY-MM-DD'), 'AA'); 


-- FOREIGN KEY 설정하기
CREATE TABLE TEST1(
	A VARCHAR2(20) PRIMARY KEY,
	B VARCHAR2(20),
	C VARCHAR2(20),
	D VARCHAR2(20)
);

CREATE TABLE TEST2(
	E VARCHAR2(20) PRIMARY KEY,
	F VARCHAR2(20),
	A VARCHAR2(20),
	CONSTRAINT TEST2_FK FOREIGN KEY(A)
		REFERENCES TEST1(A)
);

INSERT INTO TEST1 VALUES('A', 'B', 'C', 'D');
INSERT INTO TEST2 VALUES('E', 'F', 'A');

CREATE TABLE TEST3(
	G VARCHAR2(20) NOT NULL,
	H VARCHAR2(20) UNIQUE
);


CREATE TABLE SUBJECT(
	SUB_NAME VARCHAR2(50),
	SUB_NUM VARCHAR2(20),
	SUB_TIME VARCHAR2(20),
	PROFESSOR VARCHAR2(20),
	CONSTRAINT SUBNUM_PK PRIMARY KEY(SUB_NUM)
);


CREATE TABLE STUDENT(
	STUDENT_NUM NUMBER(10),
	STUDENTNAME VARCHAR2(20),
	GRADE NUMBER(1) CONSTRAINT BAN_GRADE CHECK(GRADE IN (1, 2, 3, 4, 5)),
	MAJOR VARCHAR2(20),
	CONSTRAINT STUDENTNUM_PK PRIMARY KEY(STUDENT_NUM)
);

CREATE TABLE TIMETABLE(
	CLASS_TIME VARCHAR2(20),
	CLASSROOM VARCHAR2(20),
	SUB_NAME VARCHAR2(20),
	SUB_NUM VARCHAR2(20),
	STUDENT_NUM NUMBER(10),
	CONSTRAINT CLASSTIME_PK PRIMARY KEY(CLASS_TIME),
	CONSTRAINT SUBNUM_FK FOREIGN KEY(SUB_NUM)
		REFERENCES SUBJECT(SUB_NUM),
	CONSTRAINT STUDENTNUM_FK FOREIGN KEY(STUDENT_NUM)
		REFERENCES STUDENT(STUDENT_NUM)
);



SELECT * FROM STUDENT;
SELECT * FROM SUBJECT;
SELECT * FROM TIMETABLE;