SELECT SYSDATE FROM DUAL;

CREATE TABLE CAR(
	CARNUM NUMBER(4) PRIMARY KEY,
	COLOR VARCHAR2(20),
	BRAND VARCHAR2(20),
	PRICE NUMBER(10)
);

DROP TABLE CAR;

ALTER TABLE CAR ADD(
	OWNER VARCHAR2(10)
);

ALTER TABLE CAR MODIFY(
	OWNER CHAR(10)
);

ALTER TABLE CAR DROP(
	OWNER
);


SELECT * FROM CAR;

CREATE TABLE BOOK(
	ISBN NUMBER(10),
	GENRE VARCHAR2(10),
	BOOKNAME VARCHAR2(20),
	AUTHOR VARCHAR2(20),
	PUBLISHER VARCHAR2(10),
	CONSTRAINT BOOK_PK PRIMARY KEY(ISBN)
);


ALTER TABLE BOOK MODIFY(
	ISBN VARCHAR2(20)
);

ALTER TABLE BOOK ADD(
	PRICE NUMBER(10)
);

ALTER TABLE BOOK DROP(PRICE);

SELECT * FROM BOOK